FROM python:3.11

# Set working directory
WORKDIR /app

RUN pip install --upgrade pip && \
    pip install --no-cache-dir instructlab==0.16.1

# Copy project files to the working directory
COPY . .

EXPOSE 8000

ENV CHAT_MODEL_FAMILY="merlinite"
ENV CHAT_MODEL_PATH="/mnt/models/merlinite-7b-lab-Q4_K_M.gguf"

# Run the chat server with the specified model family and model file
CMD ["sh", "-c", "ilab serve --model-family ${CHAT_MODEL_FAMILY} --model-path ${CHAT_MODEL_PATH}"]
