apiVersion: apps/v1
kind: Deployment
metadata:
  name: pathservice
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      automountServiceAccountToken: false
      containers:
        - name: pathservice
          image: quay.io/instructlab-ui/pathservice:main
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 200Mi
          ports:
            - name: http
              protocol: TCP
              containerPort: 4000
      restartPolicy: Always
